### ISSUE TITLE
Upload stalls for multi-GB files

### ISSUE THREAD

**Issue by sloth77** [prasmussen/gdrive#90]
Hi.

I'm getting stalled uploads for very large files (~10-15GB).  Seems to upload fine for a while and then throughput drops from maxing my connection at ~15Mbps to around a few Kbps.  I've tried this from two different networks (home & work) and the same issue occurs.

AFAICT, the "drive" application is still functioning, just uploading at a very slow rate all of a sudden.  Restarting the upload and the throughput is back to full.  I've checked my Google account and I have plenty of space available.

The same doesn't seem to occur for downloads, although they are around 3 or 4 times faster on my connection, so perhaps the application isn't left running for long enough.

Any ideas?

**Comment by Drezzler** [comment]
Google drive api has been unstable lately , i have been having problems with the api every few days , which gets resolved on its own.

First few times when i had similar issues , i thought something was wrong at my end , but after going through the same cycle a number of time , i have realised that the problem is with the drive api and not gdrive.

**Comment by sloth77** [comment]
Thanks Drezzler - good to know its not just me :-)

I might try splitting up the files into smaller chunks and see if that helps.

**Comment by prasmussen** [comment]
If you are still having this issue you could try gdrive 2 which uses the new v3 of the drive api.
